### ISSUE TITLE
Please align namespace name to MakeCode naming conventions.

### ISSUE THREAD

**Issue by pelikhan** [KitronikLtd/pxt-kitronik-viewtext32#1]
https://github.com/KitronikLtd/pxt-kitronik-viewtext32/blob/766b1bbb4de30d5decc4ebd87e9eae3bb657aa9f/viewtext32.ts#L7

https://makecode.com/extensions/naming-conventions

**Comment by KitronikLtd** [comment]
The namespace aligns with all the other packages that has previous been done.  The kitronik interface for fischertechnik was released with the namespace as Kitronik_IFF.

**Comment by pelikhan** [comment]
Please follow MakeCode naming conventions in the future.
