### ISSUE TITLE
block format is typically lower cased

### ISSUE THREAD

**Issue by pelikhan** [KitronikLtd/pxt-kitronik-viewtext32#3]
https://github.com/KitronikLtd/pxt-kitronik-viewtext32/blob/b9c110f78622c695a0635271bc63be7014a2dd90/viewtext32.ts#L171

https://makecode.com/extensions/naming-conventions

**Comment by KitronikLtd** [comment]
all capitals removed from each //%block="... strings
repo has been updated with change
