### ISSUE TITLE
Include .hex file in the release

### ISSUE THREAD

**Issue by kaloyan-raev** [KitronikLtd/pxt-kitronik-viewtext32#4]
Since this extension is not yet available in the MakeCode extensions gallery, users have to clone this repository and build it from source code.

Installing the required toolchain and following the build process is a pretty high entry bar for most users who are on the level of working with the MakeCode editor.

It would be much easier if users can download the ready .hex file with the extension directly from the Github releases.

**Comment by DaveAtKitronik** [comment]
resolved - extension is approved
