### ISSUE TITLE
Support for micropython (It is supported read comments!)

### ISSUE THREAD

**Issue by AirplanegoBrr** [KitronikLtd/pxt-kitronik-viewtext32#7]
Please add support for micropython! Or tell me how I could use this with micropython thanks!

**Comment by AirplanegoBrr** [comment]
MircoPython is this: https://python.microbit.org/v/2

**Comment by AirplanegoBrr** [comment]
(Add this to the readme.md) Soo you can! and its supported! (kinda?) [link](https://github.com/KitronikLtd/micropython-microbit-kitronik-text32) just use **from VIEW_TEXT32 import *** to import/use it. Make sure to comment out the lines 109-115. Also just read the VIEW_TEXT32.py to understand more commands that arnt in the readme.md!

**Comment by KitronikLtd** [comment]
added a pointer link to the readme, which closes this
